name: Generate Help Center Sitemap

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * 1"  # every Monday at 03:17 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow pushing updated sitemap back to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate sitemap
        run: |
          python -V
          python generate_helpcenter_sitemap.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add help-center-sitemap.xml
            git commit -m "Update help center sitemap [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
