name: Generate Help Center Sitemap

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * 1"  # every Monday at 03:17 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow pushing updated sitemap back to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate sitemap
        run: |
          python -V
          python generate_helpcenter_sitemap.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add help-center-sitemap.xml
            git commit -m "Update help center sitemap [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Send email notification
        if: success()  # only send if the workflow succeeded
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Pie Help Center Sitemap Updated"
          to: "paul.dandurand@piematrix.com"
          from: "Pie Sitemap Bot <paul.dandurand@piematrix.com>"
          body: |
            The sitemap update workflow completed successfully.

            - Repository: ${{ github.repository }}
            - Run ID: ${{ github.run_id }}
            - Triggered by: ${{ github.actor }}
            - View details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
